Практическое задание №6
1. Решите линейную систему:

In [2]:
import numpy as np

In [4]:
A = np.array([[1,2,3],[4,0,6],[7,8,9]])
B = np.array([12,2,1])
np.linalg.solve(A, B)

array([-9.2       ,  0.9       ,  6.46666667])

2. Найдите псевдорешение:
x + 2y – z = 1
3x – 4y = 7
8x – 5y + 2z = 12
2x – 5z = 7
11x +4y – 7z = 15

In [5]:
K = np.array([[1, 2, -1], [3, -4, 0], [8, -5, 2], [2, -5, 0], [11, 4, -7]])
M = np.array([1, 7, 12, 7, 15])

In [12]:
S = np.linalg.lstsq(K, M, rcond=None)[0]
S

array([ 1.15601029, -0.889718  , -0.85029782])

In [13]:
np.dot(K, S) - M

array([-0.7731279 ,  0.02690287, -0.00392334, -0.23938941,  0.10932589])

 Сколько решений имеет линейная система:

In [38]:
A3 = np.array([[1,2,3],[4,5,6],[7,8,9]])
B3 = np.array([12,2,1])
print(f"solve: {np.linalg.solve(A3, B3)}, det={np.linalg.det(A3)}, rank={np.linalg.matrix_rank(A3, tol=0.001)}")

solve: [ 2.83726777e+16 -5.67453553e+16  2.83726777e+16], det=-9.51619735392994e-16, rank=2


нет решений

In [41]:
B31 = np.array([3,2,1])
S = np.linalg.solve(A3, B31)
S

array([ 0.33333333, -4.66666667,  4.        ])

In [42]:
np.dot(A3, S)

array([3., 2., 1.])

In [44]:
C3 = np.concatenate((A3, B3.reshape(-1, 1)), axis=1)
C31 = np.concatenate((A3, B31.reshape(-1, 1)), axis=1)
np.linalg.matrix_rank(C3, 0.001), np.linalg.matrix_rank(C31, 0.001)

(3, 2)

In [49]:
B32 = np.array([2,5,1])
print(f"solve: {np.linalg.solve(A3, B32)}, det={np.linalg.det(A3)}, rank={np.linalg.matrix_rank(A3, tol=0.001)}")

solve: [-2.20676382e+16  4.41352763e+16 -2.20676382e+16], det=-9.51619735392994e-16, rank=2


In [50]:
B33 = np.array([2,5,8])
print(f"solve: {np.linalg.solve(A3, B33)}, det={np.linalg.det(A3)}, rank={np.linalg.matrix_rank(A3, tol=0.001)}")

solve: [-0.2  1.4 -0.2], det=-9.51619735392994e-16, rank=2


Вычислите LU-разложение матрицы:
После этого придумайте вектор правых частей и решите полученную линейную систему трех уравнений с данной матрицей.

In [69]:
N = np.array([[1,2,3], [2,16,21], [4,28,73]])
N

array([[ 1,  2,  3],
       [ 2, 16, 21],
       [ 4, 28, 73]])

In [70]:
from scipy.linalg import lu

In [74]:
P, L, U = lu(N)
print(P, L, U, N - np.dot(P, np.dot(L, U)), sep='\n\n')

[[0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]]

[[ 1.    0.    0.  ]
 [ 0.25  1.    0.  ]
 [ 0.5  -0.4   1.  ]]

[[  4.    28.    73.  ]
 [  0.    -5.   -15.25]
 [  0.     0.   -21.6 ]]

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [73]:
np.dot(L, U)

array([[ 4., 28., 73.],
       [ 1.,  2.,  3.],
       [ 2., 16., 21.]])

In [82]:
B4 = np.array([1,12,19])

In [83]:
np.linalg.solve(N, B4)

array([-0.64351852,  0.8912037 , -0.0462963 ])

5. Найдите нормальное псевдорешение недоопределенной системы:
x + 2y – z = 1
8x – 5y + 2z = 12
Для этого определите функцию Q(x,y,z), равную норме решения, и найдите ее минимум. 


In [89]:
import matplotlib.pyplot as plt

In [92]:
F = np.array([[1, 2, -3], [8, -5, 2]])
G = np.array([1, 12])
print(np.linalg.matrix_rank(F, 0.001), np.linalg.matrix_rank(np.concatenate((F, G.reshape(-1, 1)), axis=1), 0.001))
def Q2(x, y, z):
    return x*x+y*y+z*z

2 2


In [96]:
S = np.linalg.lstsq(F, G, rcond=None)[0]
S

array([ 1.28998384, -0.40549273, -0.17366721])

In [97]:
np.dot(F, S)

array([ 1., 12.])

6. Найдите одно из псевдорешений вырожденной системы:
Попробуйте также отыскать и нормальное псевдорешение.

In [102]:
A6 = np.array([[1,2,3], [4,5,6], [7,8,9]])
B6 = np.array([2,5,11])
print(np.linalg.matrix_rank(A6, 0.001), np.linalg.matrix_rank(np.concatenate((A6, B6.reshape(-1, 1)), axis=1), 0.001))

2 3


In [101]:
np.linalg.lstsq(A6, B6, rcond=None)[0]

array([ 1.25,  0.5 , -0.25])

In [104]:
Q, R = np.linalg.qr(A6)
print(A6, Q, R, sep='\n\n')

[[1 2 3]
 [4 5 6]
 [7 8 9]]

[[-0.12309149  0.90453403  0.40824829]
 [-0.49236596  0.30151134 -0.81649658]
 [-0.86164044 -0.30151134  0.40824829]]

[[-8.12403840e+00 -9.60113630e+00 -1.10782342e+01]
 [ 0.00000000e+00  9.04534034e-01  1.80906807e+00]
 [ 0.00000000e+00  0.00000000e+00 -1.11164740e-15]]


In [105]:
np.dot(Q, Q.T)

array([[1.00000000e+00, 2.10258665e-16, 4.36991811e-16],
       [2.10258665e-16, 1.00000000e+00, 1.43069439e-16],
       [4.36991811e-16, 1.43069439e-16, 1.00000000e+00]])

In [106]:
np.dot(Q,R)

array([[1., 2., 3.],
       [4., 5., 6.],
       [7., 8., 9.]])

In [107]:
np.linalg.det(A6)

-9.51619735392994e-16

In [108]:
R1 = R[:2, :2]
R1

array([[-8.1240384 , -9.6011363 ],
       [ 0.        ,  0.90453403]])

In [112]:
B61 = np.dot(Q.T, B6)[:2]
B61

array([-1.21860576e+01,  8.54871729e-15])

In [113]:
X61 = np.linalg.solve(R1, B61)
X61

array([1.50000000e+00, 9.45096256e-15])

In [114]:
X6 = np.append(X61, 0)
print(X6, np.linalg.norm(X6))

[1.50000000e+00 9.45096256e-15 0.00000000e+00] 1.4999999999999893


In [115]:
np.linalg.norm(np.dot(A6, X6) - B6)

1.2247448713915885

...